# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiGeneIdentifiersFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('html_file', models.FileField(default='', upload_to='multi-varieties/')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleVarietiesResultsIDs',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('muscle_file', models.FileField(default='', upload_to='multi-results-ids/')),
                ('multalin_file', models.FileField(default='', upload_to='multi-results-ids/')),
                ('html_file', models.FileField(default='', upload_to='multi-results-ids/')),
                ('uniqueid', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('htmlfilelist', jsonfield.fields.JSONField(default='')),
                ('linksfile', models.FileField(default='', upload_to='multi-results-ids/')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsGeneIdentifiers',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('consensus_file', models.FileField(default='', upload_to='results-geneids/')),
                ('uniqueid', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('species_name', models.CharField(blank=True, max_length=100)),
                ('species_file', models.FileField(upload_to='species/')),
                ('location', models.CharField(default='input', max_length=200, verbose_name='species/')),
            ],
            options={
                'ordering': ['species_name'],
            },
        ),
        migrations.CreateModel(
            name='SubmitGeneIdentifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('inputTYPE', models.TextField()),
                ('organism', models.TextField()),
                ('geneid', models.TextField()),
                ('outputfmt', models.TextField()),
                ('jobid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('submitted_time', models.TimeField(auto_now_add=True)),
                ('uuid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmitSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('organism', models.TextField()),
                ('sequence', models.TextField()),
                ('outputfmt', models.TextField()),
                ('jobid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('submitted_time', models.TimeField(auto_now_add=True)),
                ('uuid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('variety_name', models.CharField(blank=True, max_length=100)),
                ('variety_consensus', models.FileField(upload_to='varieties/')),
                ('location', models.CharField(default='varieties', max_length=200, verbose_name='varieties/')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='debaserapp.Species')),
            ],
            options={
                'ordering': ['variety_name'],
            },
        ),
        migrations.AddField(
            model_name='submitsequence',
            name='varieties',
            field=models.ManyToManyField(related_name='submitted_sequence', to='debaserapp.Variety'),
        ),
        migrations.AddField(
            model_name='submitgeneidentifiers',
            name='varieties',
            field=models.ManyToManyField(related_name='submitted_geneid', to='debaserapp.Variety'),
        ),
    ]
