# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-08 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debaserapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsgeneidentifiers',
            name='consensuslink',
            field=models.FileField(default='', upload_to='results-geneids/'),
        ),
    ]
