# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debaserapp', '0003_resultsgeneidentifiers_reportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplevarietiesresultsids',
            name='consensus_file',
            field=models.FileField(default='', upload_to='multi-results-ids/'),
        ),
    ]
